# ======================================
# Gradle performance
# ======================================
org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=true
# ======================================
# Android
# ======================================
android.useAndroidX=true
android.nonTransitiveRClass=true
# ======================================
# Kotlin
# ======================================
kotlin.code.style=official
kotlin.incremental=true
# ======================================
# R8 / Shrinker
# ======================================
android.enableR8.fullMode=false
